# Copyright (C) 2021 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Aufruf:   i.a. bereits eingestellt:   $env:SKAFFOLD_PROFILE = 'dev'
#                                       $env:TAG = '2024.04.0-buildpacks'
#           skaffold dev
#           skaffold delete
#           docker tag ahmadhawarnah/faculty:2024.04.0-buildpacks ahmadhawarnah/faculty:latest

# https://skaffold.dev/docs/references/yaml
# https://skaffold-latest.firebaseapp.com/docs/references/yaml

# https://github.com/GoogleContainerTools/skaffold/tree/master/docs/content/en/schemas
apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: faculty
# https://skaffold.dev/docs/pipeline-stages/builders
build:
  artifacts:
    - image: ahmadhawarnah/faculty
      # https://skaffold.dev/docs/pipeline-stages/builders/buildpacks
      # https://paketo.io/docs/howto/java
      # https://www.youtube.com/watch?v=aI19ZYV4-7o
      buildpacks:
        builder: paketobuildpacks/builder:base
        env: [BP_JVM_VERSION=21.*]
        dependencies:
          paths: [src, build.gradle.kts]
  # https://skaffold.dev/docs/pipeline-stages/taggers
  tagPolicy:
    envTemplate:
      template: "{{.TAG}}"
deploy:
  # https://skaffold.dev/docs/pipeline-stages/deployers/helm
  # Alternativen: Kustomize, kpt, kubectl
  helm:
    releases:
      - name: faculty
        chartPath: extras/kubernetes/faculty
        valuesFiles: [extras/kubernetes/faculty/values.yaml]
        namespace: acme
profiles:
  - name: dev
    activation:
      - env: SKAFFOLD_PROFILE=dev
    deploy:
      helm:
        releases:
          - name: faculty
            chartPath: extras/kubernetes/faculty
            #valuesFiles: [extras/kubernetes/faculty/values.yaml, extras/kubernetes/faculty/dev.yaml]
            #valuesFiles: [extras/kubernetes/faculty/values.yaml, extras/kubernetes/faculty/dev.yaml, extras/kubernetes/faculty/dev-mysql.yaml]
            valuesFiles: [extras/kubernetes/faculty/values.yaml, extras/kubernetes/faculty/dev.yaml, extras/kubernetes/faculty/dev-h2.yaml]
            namespace: acme
    # https://skaffold.dev/docs/pipeline-stages/port-forwarding
    portForward:
      - resourceType: service
        resourceName: faculty
        port: http-svc
