autoscaling:
  maxReplicas: 1

replicaCount: 1
rollingUpdate:
  maxUnavailable: 0

progressDeadlineSeconds: 90

image:
  pullPolicy: IfNotPresent

profile: dev
ssl: "false"
http2: "false"

resourcesRequests:
  #cpu: 1000m
  memory: 768Mi
  #memory: 1536Mi

resourcesLimits:
  #cpu: 2000m
  memory: 768Mi
  #memory: 1536Mi

livenessProbe:
  #initialDelay: 45
  initialDelay: 75
  #timeout: 15
  timeout: 30
  period: 180
  #failureThreshold: 1
  failureThreshold: 2
readinessProbe:
  #initialDelay: 45
  initialDelay: 75
  #timeout: 15
  timeout: 30
  period: 180
  #failureThreshold: 1
  failureThreshold: 2

h2:
  console:
    enabled: "false"
